### PR TITLE
 🔰 updated installation instruction for ARM7

### PR DESCRIPTION
**Pull request by the-mcnaveen**
🔰 updated installation instruction for ARM7 (Ex. Raspberry Pi)

### CODE REVIEW

**Comment by jmattheis** [comment]
Hey @the-mcnaveen,
Thanks for your contribution!

Do we really need an extra section for arm? I mean, the only difference is, that another zip must be downloaded.

**Comment by the-mcnaveen** [comment]
Well, While I started using Gotify in Pi. Faced this issue, Because Previously I'm using Gotify in my Laptop. I checked the Documentation isn't there.

So I came up with a Blog Post explaining this stuff. [Here](https://letsfoss.com/setting-up-gotify-in-raspberry-pi/)

#28 Closed this PR because it had a link to my blog post and created new PR #29 thought of helping newbie/starters.

Hoping for Good and Better Documentation :smile:

**Comment by the-mcnaveen** [comment]
Any Update? Shall I close this Pull Request?

**Comment by jmattheis** [comment]
Hey @the-mcnaveen, sorry for the late response.

We could add a placeholder for the name of the binary/zip file and then use this placeholder in the rest of the binary docs to not duplicate chmod and execute. Would you like to do this? Otherwise, I'll do it later.

**Comment by the-mcnaveen** [comment]
Sure. That's awesome. Your suggestion looks great. 

Waiting to see the Change in Docs. 💖

**Comment by the-mcnaveen** [comment]
Sure. That's awesome. Your suggestion looks great. 

Waiting to see the Change in Docs. 💖

**Comment by jmattheis** [comment]
FYI: Added it with https://github.com/gotify/website/commit/5bd83db84b5619b7f3fca9540374c809ae6db9a0

**Pull request closed without merging**
