### PR TITLE
Add documentation on running gotify as a service

### LINKED ISSUE #14: Better "Getting started"
Cover things like:

1. Downloading binary from releases page
2. Unzip it
3. Assign permissions
4. Setup to run as a service
5. Config file/first start

### PR DESCRIPTION
**Pull request by fkellner**
Basically what https://github.com/gotify/website/issues/14#issue-421625126 requested - a small guide on how to run gotify as a service on a linux system that uses systemd as service manager. 
Has been tested to work on Ubuntu Server 18.04.

Fixes #14

### CODE REVIEW

**Comment by fkellner** [comment]
Okay, found the problem, will try again with a new request. You should document that prettying is required.

**Comment by jmattheis** [comment]
Thanks for your contribution! 

I feel like this "tutorial" is a little complicated, first we create files, then we move them via a shell script. I think think most of the stuff could be created directly where it belongs (f.ex. the gotify config directly to /etc/gotify/config.yml). What do you think?

It could be something like.
* Create config file in /etc/gotfiy/config.yml
* Create user
* Create directories && chown
* Copy bin
* Create gotify.service
* start/stop service, logs, etc.
* How to remove gotify

Like this, no shell scripts are needed and its pretty easy to understand why things are done.

**Comment by fkellner** [comment]
Well, to be honest, I still think that distributing the gotify.service file, the systemd-config.yml and the installer/uninstaller scripts with the linux binaries would be the simplest way for users to run your application as a service.

That way, users would just need to execute one single script that writes everything they need to know to stdout (and if they are really wondering they can open it and see the comments), and I could make it even more foolproof by checking in beforehand if systemd is installed and failing the whole script if something does not work as expected.

I think that although copying the whole thing command for command from a website might help users better understand what is happening, how to create a service from an executable is probably better documented elsewhere, and it would also be nice to be able to uninstall something without needing an internet connection to view a website (because, let's face it, nobody will remember all the steps).

That being said, I think you are right and the tutorial is complicated, and once I have time (probably sometime next week), I can try to make the tutorial more readable by adhering to your feedback ;)

**Comment by jmattheis** [comment]
@fkellner Okay, different proposal. You could add your files to a repo and link it in https://github.com/gotify/contrib and gotify/website, like this, the user only has to wget the files/clone the repo to manage gotify with systemd.

**Comment by hypervtechnics** [comment]
Maybe as a contribution from my side, who initiated #14.

I made [this](https://gist.github.com/hypervtechnics/9cb28e67aea93cb9b87af5141bc3aa25) guide during the last days. Maybe we can adapt something from there?

**Comment by jmattheis** [comment]
Yeah, I think we could link your tutorial on gotify/contrib, then users should be able to find it.

**Comment by geeseven** [comment]
Slightly off topic.  @hypervtechnics, you should add the Caddy configuration to [caddyserver/examples][0] and the Gotify documentation.  

[0]: https://github.com/caddyserver/examples

**Pull request closed without merging**
