### PR TITLE
Add Haproxy proxy documentation

### PR DESCRIPTION
**Pull request by minecraftchest1**

### CODE REVIEW

**Comment by jmattheis** [comment]
Sorry overlooked the PR, I've added some timeouts and removed the sub path thing as it didn't work. It still needs some kind of path rewriting and I don't know how to do this with haproxy. Feel free to create a new PR for this.

**Comment by minecraftchest1** [comment]
Thanks. I think I tested the subpath to see if haproxy complined, but I don't think I actually tested it. I'll work on that and open a new pr.

**Comment by jmattheis** [comment]
@minecraftchest1 I've the basics, but the websocket connection doesn't work (it breaks with mode http, but mode http is needed for http-request replace-path):
```
frontend frontend_gotify
        bind 0.0.0.0:80
        use_backend backend_gotify if { path -i -m beg /gotify/ }
        timeout client 60s

backend backend_gotify
        mode http
        http-request replace-path /gotify/(.*) /\1
        server  backend01       gotify:80  check
        timeout connect 10s
        timeout server 60s
```

**Comment by minecraftchest1** [comment]
@jmattheis What issue were you having with the subpath for gotify?

**Pull request closed without merging**
