### PR TITLE
Update pushmsg.md

### PR DESCRIPTION
**Pull request by ethanholz**
- Consistent docs with gotify CLI

### CODE REVIEW

**Comment by jmattheis** [comment]
This was removed in https://github.com/gotify/website/pull/57, it shouldn't be re-added.

**Comment by ethanholz** [comment]
@jmattheis I believe this may have been closed prematurely. The file referenced in #57 is only in reference to the more-pushmsg.md file not the one listed in my PR. This example noted in the pushmsg.md file does not work as there is no reference to a POST request at all thus, it is not redundant. We can either add the --data flag or add the option noted in my PR.

**Comment by jmattheis** [comment]
Yeah, sorry, referenced the wrong PR https://github.com/gotify/website/pull/31

The example *without* `-X POST` works fine on my system:
```
$ curl "http://localhost:8080/message?token=A51DTcEH99U2mOq" -F "message=my message" -vv
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /message?token=A51DTcEH99U2mOq HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.86.0
> Accept: */*
> Content-Length: 152
> Content-Type: multipart/form-data; boundary=------------------------f5d67905f2984e64
>
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 29 Nov 2022 17:43:30 GMT
< Content-Length: 114
<
* Connection #0 to host localhost left intact
{"id":243,"appid":10,"message":"my message","title":"aa","priority":0,"date":"2022-11-29T18:43:30.51345332+01:00"}%
```
-F automatically force a POST request: https://curl.se/docs/manpage.html#-F

> For HTTP protocol family, this lets curl emulate a filled-in form in which a user has pressed the submit button. This causes curl to POST data using the Content-Type multipart/form-data according to [RFC 2388](http://www.ietf.org/rfc/rfc2388.txt).

**Comment by ethanholz** [comment]
Ahhh my bad. Thanks for the quick response!

**Pull request closed without merging**
