### PR TITLE
Add Render deploy guide

### PR DESCRIPTION
**Pull request by anurag**
Just discovered Gotify and blown away by how easy it is to set up. Added a 'Deploy on Render' guide based on https://github.com/render-examples/gotify-server to make it even easier for users to get started with Gotify in production.

### CODE REVIEW

**Comment by jmattheis** [comment]
Hey @anurag,

thanks for adding Gotify to render! It seems like a simple way to deploy Gotify.

Sadly I don't think this should be included into the Gotify documentation. Render is a paid service and also closed source (as far as I see). 
Gotify should be completely free and therefore render doesn't really fit into the Gotify ecosystem.

However, there is a [gotify/contrib](https://github.com/gotify/contrib) repository. In there a link to render could be added.

**Comment by anurag** [comment]
Understood. I still maintain it's very useful to have a 'Deployment Options' section where users can find easy ways to deploy the server. Gotify users still need hosting (which is almost always paid), and they struggle with nginx/Apache configuration which is all taken care of by Render.

Other OSS projects offer this as well: for example, Docusaurus has this section on their site mentioning commercial deployment options like GitHub Pages and Netlify: https://docusaurus.io/docs/en/publishing .

But I'll open a contrib/ PR for now.

**Comment by jmattheis** [comment]
@anurag Sorry for replying this late, just wanted to say that GitHub pages and Netlify provide free hosting. gotify.net is hosted via github pages, it doesn't cost me anything.

**Comment by anurag** [comment]
> @anurag Sorry for replying this late, just wanted to say that GitHub pages and Netlify provide free hosting. gotify.net is hosted via github pages, it doesn't cost me anything.

No worries! For what it's worth, Render also offers completely free hosting for static sites (just like GitHub Pages and Netlify). We only charge for services that require a backend server.

**Pull request closed without merging**
