### PR TITLE
Adding configuration for apache2

### PR DESCRIPTION
**Pull request by monsieurpouet**

### CODE REVIEW

**Comment by monsieurpouet** [comment]
OK :) I'm learning github, so.. :D
I'll do this soon !

**Comment by monsieurpouet** [comment]
```
> @ format /home/theo/Documents/website/website
> prettier ../docs/*.md **/*.js *.js ../README.md --write

sh: 1: prettier: not found

npm ERR! Linux 4.15.0-42-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "format"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ format: `prettier ../docs/*.md **/*.js *.js ../README.md --write`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ format script 'prettier ../docs/*.md **/*.js *.js ../README.md --write'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prettier ../docs/*.md **/*.js *.js ../README.md --write
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/theo/Documents/website/website/npm-debug.log
```

Hum it seems bad :/

**Comment by monsieurpouet** [comment]
> @ format /home/theo/Documents/website/website
> prettier ../docs/*.md **/*.js *.js ../README.md --write

../docs/apache.md 121ms
../docs/configuration.md 79ms
../docs/dev-environment.md 46ms
../docs/index.md 15ms
../docs/installation.md 35ms
../docs/more-pushmsg.md 15ms
../docs/nginx.md 10ms
../docs/pushmsg.md 31ms
../docs/swagger-docs.md 13ms
core/Footer.js 101ms
siteConfig.js 15ms
../README.md 8ms

Its seems good for me :o

**Comment by jmattheis** [comment]
@monsieurpouet On my machine (and also on travis-ci) prettier removes whitespaces. see https://github.com/gotify/website/commit/ff232f18b3c9485022094638a1ce25a98f819c0a

If that doesn't work for you feel free to cherry-pick my commit.

**Comment by jmattheis** [comment]
Will be done in #4.

**Pull request closed without merging**
